@startuml
'https://plantuml.com/sequence-diagram

title Админ-панель
== Создание, изменение, удаление шаблонов, контента уведомлений, списков рассылок ==
autonumber
Admin -> Admin_view ++ : Создание, изменение, удаление:\nшаблонов, контента уведомлений,\nсписков рассылок
Admin_view -> Notification_DB ++ : CRUD шаблонов,\nконтента уведомлений,\nсписков рассылок
Admin_view <-- Notification_DB -- : Success
Admin <-- Admin_view -- : Done
== Предпросмотр шаблонов рассылки или уведомлений ==
autonumber
Admin -> Admin: Выбор шаблона рассылки\n или уведомления
Admin -> Admin_view: Предпросмотр шаблона рассылки\n с данными менеджера
Admin_view -> Async_search_API ++ : Запрос информации о фильмах,\nжанрах, актерах для предпросмотра
Admin_view -> UGC_API ++ : Запрос агрегированной\nпользовательской статистики\n или изменений для предпросмотра
Admin_view <-- Async_search_API -- : Получение информации о\nфильмах, жанрах, актерах
Admin_view <-- UGC_API -- : Получение агрегированной\nпользовательской статистики\n или изменений
Admin_view -> Admin_view: Создание представления\nсообщения уведомления\n на основе собранных данных
== Создание немедленной рассылки уведомлений ==
autonumber
Admin -> Admin: Выбор шаблона уведомлений\nдля рассылки
Admin -> Admin_view: Проверка/изменение параметров\n рассылки (шаблон, контент,\nсписок рассылки)
Admin -> Admin_view: Выбор режима отправки\n"Немедленная отправка"
Admin -> Admin_view: Сохранение рассылки\n(Кнопка "Сохранить|Запустить")
Admin_view -> Notification_DB: Сохранение рассылки\n в базу данных со статусом\n "to_immediate_send"
Admin_view -> Notification_API ++ : http-запрос с параметром\nnotification_id рассылки
Admin_view <-- Notification_API -- : http-ответ "Acknowledge notification_id"
note right : Дальнейшая обработка запроса осуществляется \n API сервиса нотификации и воркерами
Admin_view --> Admin: Статус рассылки "in_processing"
note over Admin, Notification_DB
После успешного завершения обработки рассылки API сервиса
нотификации и воркерами рассылка помечается как завершенная
(статус рассылки в БД меняется на "completed")
end note
== Создание рассылки уведомлений по расписанию (периодической рассылки) ==
autonumber
Admin -> Admin: Выбор шаблона уведомлений\nдля рассылки
Admin -> Admin_view: Проверка/изменение параметров\n рассылки (шаблон, контент,\nсписок рассылки)
Admin -> Admin_view: Выбор режима отправки\n"Отправка по расписанию"
Admin -> Admin_view: Выбор расписания для отправки
Admin -> Admin_view: Сохранение рассылки\n(Кнопка "Сохранить|Запустить")
Admin_view -> Notification_DB: Сохранение рассылки\n в базу данных со статусом\n "to_scheduled_send"
note right : Дальнейшая обработка рассылки осуществляется\n планировщиком автоматических событий
Admin_view --> Admin: Статус рассылки "await_processing"
note over Admin, Notification_DB
После начала обработки рассылки планировщиком автоматических
событий статус рассылки меняется на "in_processing". После
успешного завершения обработки рассылка помечается как завершенная
(статус рассылки в БД меняется на "completed")
end note
@enduml