# Generated by Django 3.2.13 on 2022-05-10 19:01

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('title', models.CharField(max_length=120, null=True, verbose_name='наименование шаблона уведомления')),
                ('subject', models.CharField(blank=True, max_length=120, null=True, verbose_name='тема уведомления')),
                ('from_email', models.CharField(blank=True, max_length=120, null=True, verbose_name='электронная почта отправителя')),
                ('html_template', tinymce.models.HTMLField(blank=True, null=True, verbose_name='содержание html-шаблона')),
                ('plain_text', models.TextField(blank=True, null=True, verbose_name='содержание текстового шаблона')),
                ('is_html', models.BooleanField(default=False)),
                ('is_text', models.BooleanField(default=False)),
                ('template_key', models.CharField(choices=[('weekly_personal_mailing_movies', 'еженедельная персональная подборка фильмов'), ('monthly_personal_statistic_views', 'ежемесячная персональная статистика просмотров'), ('daily_personal_statistic_likes', 'ежедневная персональная статистика по лайкам рецензий'), ('email_confirmation', 'подтверждение адреса электронной почты при регистрации')], max_length=50, verbose_name='вид шаблона')),
                ('adapter', models.CharField(choices=[('email', 'Email'), ('sms', 'Sms'), ('websocket', 'Websocket')], default='email', max_length=50, verbose_name='используемый адаптер для отправки уведомления')),
            ],
            options={
                'verbose_name': 'шаблон уведомления',
                'verbose_name_plural': 'шаблоны уведомлений',
                'db_table': 'notification"."templates',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MailingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('status', models.CharField(choices=[('To immediate send', 'для немедленной отправки'), ('To scheduled send', 'для отправки планировщиком'), ('In processing', 'в процессе обработки'), ('Completed', 'успешно завершена'), ('Cancelled', 'отменена')], default='To scheduled send', max_length=250, verbose_name='статус рассылки')),
                ('is_promo', models.BooleanField(default=True, verbose_name='рекламная рассылка')),
                ('priority', models.CharField(choices=[('high', 'высокий приоритет'), ('medium', 'средний приоритет'), ('low', 'низкий приоритет')], default='low', max_length=30, verbose_name='приоритет рассылки')),
                ('context', models.JSONField(default={}, verbose_name='контекст рассылки')),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True, verbose_name='плановые дата и время рассылки')),
                ('repeat_frequency', models.CharField(choices=[('daily', 'ежедневно'), ('weekly', 'еженедельно'), ('monthly', 'ежемесячно')], max_length=20, verbose_name='периодичность рассылки')),
                ('execution_datetime', models.DateTimeField(blank=True, null=True, verbose_name='фактическое время завершения рассылки')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.template', verbose_name='шаблон уведомления')),
            ],
            options={
                'verbose_name': 'задача рассылки',
                'verbose_name_plural': 'задачи рассылки',
                'db_table': 'notification"."mailing_tasks',
                'managed': True,
            },
        ),
    ]
