# Generated by Django 3.2.13 on 2022-05-12 15:19
# type: ignore
import uuid

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('template_type', models.CharField(choices=[('weekly_new_movies', 'еженедельная подборка новых фильмов'), ('monthly_personal_statistic', 'ежемесячная статистика просмотров'), ('daily_personal_statistic', 'ежедневная статистика по лайкам рецензий'), ('wellcome_letter', 'приветственное письмо при регистрации')], max_length=50, verbose_name='вид шаблона')),
                ('title', models.CharField(max_length=120, null=True, verbose_name='наименование шаблона уведомления')),
                ('subject', models.CharField(blank=True, max_length=120, null=True, verbose_name='тема уведомления')),
                ('from_email', models.CharField(blank=True, max_length=120, null=True, verbose_name='электронная почта отправителя')),
                ('html_template', tinymce.models.HTMLField(blank=True, null=True, verbose_name='содержание html-шаблона')),
                ('plain_text', models.TextField(blank=True, null=True, verbose_name='содержание текстового шаблона')),
                ('is_html', models.BooleanField(default=False)),
                ('is_text', models.BooleanField(default=False)),
                ('channel', models.CharField(choices=[('email', 'Электронная почта'), ('sms', 'SMS'), ('websocket', 'Websocket'), ('push', 'Push-уведомления')], default='email', max_length=50, verbose_name='канал для отправки уведомления')),
            ],
            options={
                'verbose_name': 'шаблон уведомления',
                'verbose_name_plural': 'шаблоны уведомлений',
                'db_table': 'notification"."templates',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MailingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('service', models.CharField(default='admin_panel', max_length=10, verbose_name='источник рассылки')),
                ('title', models.CharField(max_length=120, null=True, verbose_name='наименование рассылки')),
                ('type_mailing', models.CharField(choices=[('To immediate send', 'для немедленной отправки'), ('To scheduled send', 'для отправки планировщиком')], default='To scheduled send', max_length=250, verbose_name='вид рассылки')),
                ('status', models.CharField(choices=[('Pending', 'ожидает обработки'), ('In processing', 'в процессе обработки'), ('Completed', 'успешно завершена'), ('Cancelled', 'отменена')], default='Pending', max_length=250, verbose_name='статус рассылки')),
                ('is_promo', models.BooleanField(default=True, verbose_name='рекламная рассылка')),
                ('priority', models.CharField(choices=[('high', 'высокий приоритет'), ('medium', 'средний приоритет'), ('low', 'низкий приоритет')], default='low', max_length=30, verbose_name='приоритет рассылки')),
                ('context', models.JSONField(default=dict, verbose_name='контекст рассылки')),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True, verbose_name='плановые дата и время рассылки')),
                ('execution_datetime', models.DateTimeField(blank=True, null=True, verbose_name='фактическое время завершения рассылки')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.template', verbose_name='шаблон уведомления')),
            ],
            options={
                'verbose_name': 'задачу рассылки',
                'verbose_name_plural': 'задачи рассылки',
                'db_table': 'notification"."mailing_tasks',
                'managed': True,
            },
        ),
    ]
