# Generated by Django 3.2.13 on 2022-05-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingtask',
            name='title',
            field=models.CharField(max_length=120, null=True, verbose_name='наименование рассылки'),
        ),
    ]
