# Generated by Django 3.2.13 on 2022-05-12 15:20
# type: ignore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingtask',
            name='service',
            field=models.CharField(default='admin_panel', max_length=50, verbose_name='источник рассылки'),
        ),
    ]
