# Generated by Django 3.2.13 on 2022-05-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_mailingtask_service'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mailingtask',
            constraint=models.Index(fields=['service', 'status'], name='ix__mailing_tasks__service_status'),
        ),
        migrations.AddConstraint(
            model_name='mailingtask',
            constraint=models.Index(fields=['status'], name='ix__mailing_tasks__status'),
        ),
        migrations.AddConstraint(
            model_name='mailingtask',
            constraint=models.Index(fields=['scheduled_datetime'], name='ix__mailing_tasks__scheduled_datetime'),
        ),
        migrations.AddConstraint(
            model_name='mailingtask',
            constraint=models.Index(fields=['execution_datetime'], name='ix__mailing_tasks__execution_datetime'),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.Index(fields=['template_type', 'channel'], name='ix__templates__template_type_channel'),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.Index(fields=['subject'], name='ix__templates__subject'),
        ),
    ]
