version: "3.8"
   
services:
  db:
    image: postgres:13.0
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
  web:
    build: ./notification_admin
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./notification_admin/:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db